defmodule AshTwitter.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:likes, primary_key: false) do
      add :author_id,
          references(:authors,
            column: :id,
            name: "likes_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :tweet_id,
          references(:tweets,
            column: :id,
            name: "likes_tweet_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:likes, "likes_author_id_fkey")

    drop constraint(:likes, "likes_tweet_id_fkey")

    drop table(:likes)
  end
end