defmodule AshTwitter.Support.Tweet do
  # This turns this module into a resource
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  alias AshTwitter.Support.Author
  alias AshTwitter.Support

  postgres do
    table "tweets"
    repo AshTwitter.Repo
  end

  actions do
    # Add a set of simple actions. You'll customize these later.
    defaults [:read, :update, :destroy]

    create :create do
      primary?(true)

      argument :author_id, :uuid do
        allow_nil?(false)
      end

      change(set_attribute(:author_id, arg(:author_id)))
    end
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :content, :string
  end

  relationships do
    belongs_to :author, Author do
      api Support
      allow_nil? false
    end
  end
end
